# TODO (Person 1 - AI): Implement LLM integration with streaming responses
# Manage system prompts, call Gemini/OpenAI API, and stream token chunks.

import os
from google import genai

class LLMService:
    def __init__(self):
        # We read the API key from the environment
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            print("WARNING: GEMINI_API_KEY not found in environment variables.")
        
        # The new Google GenAI SDK
        self.client = genai.Client(api_key=api_key)
        self.model_id = 'gemini-2.5-flash'
        
    def generate_response_basic(self, prompt: str, rag_context: str = "") -> str:
        """A non-streaming call to verify Gemini is working, optionally using RAG context."""
        
        system_instruction = (
            "You are an expert, professional Business English tutor. Your goal is to help the user "
            "communicate effectively, politely, and formally in a corporate setting.\n\n"
            "RULES:\n"
            "1. Identify any grammar, spelling, or phrasing mistakes in the user's input.\n"
            "2. Gently correct the mistakes.\n"
            "3. Provide 2-3 more professional alternatives that sound natural in a business context.\n"
            "4. If relevant, incorporate the provided Curriculum Context to explain grammar rules.\n"
            "5. Keep your tone encouraging and concise."
        )

        if rag_context:
            system_instruction += f"\n\nCURRICULUM CONTEXT:\n{rag_context}"
        
        response = self.client.models.generate_content(
            model=self.model_id,
            contents=prompt,
            config=genai.types.GenerateContentConfig(
                system_instruction=system_instruction
            )
        )
        
        return response.text
        
    async def generate_response_stream(self, prompt: str, rag_context: str = ""):
        """An async generator that streams token chunks as they are generated by Gemini."""
        
        system_instruction = (
            "You are an expert, professional Business English tutor. Your goal is to help the user "
            "communicate effectively, politely, and formally in a corporate setting.\n\n"
            "RULES:\n"
            "1. Identify any grammar, spelling, or phrasing mistakes in the user's input.\n"
            "2. Gently correct the mistakes.\n"
            "3. Provide 2-3 more professional alternatives that sound natural in a business context.\n"
            "4. If relevant, incorporate the provided Curriculum Context to explain grammar rules.\n"
            "5. Keep your tone encouraging and concise."
        )

        if rag_context:
            system_instruction += f"\n\nCURRICULUM CONTEXT:\n{rag_context}"
        
        # We use the async client (self.client.aio) to avoid blocking the event loop
        response_stream = await self.client.aio.models.generate_content_stream(
            model=self.model_id,
            contents=prompt,
            config=genai.types.GenerateContentConfig(
                system_instruction=system_instruction
            )
        )
        
        # Yield each chunk of text as it arrives from Google
        async for chunk in response_stream:
            if chunk.text:
                yield chunk.text
